### ISSUE TITLE
Assertions for free groups

### ISSUE THREAD

**Issue by siddhartha-gadgil** [siddhartha-gadgil/ProvingGround#10]
Required for both case classes and parser constructors. As a bonus can be used for pattern matching after wrapping in Try.

**Comment by Bolt64** [comment]
Done so for the case classes. But where do the parser constructors come in?

**Comment by siddhartha-gadgil** [comment]
When parsing strings to words etc, if we have assertions for being valid, we can wrap parsing in a Try and to option to define an unapply method
