### ISSUE TITLE
implicit based recursion for given codomain

### ISSUE THREAD

**Issue by siddhartha-gadgil** [siddhartha-gadgil/ProvingGround#102]
- Instead of existential types, we return using _implicit_ proofs so that refined types are known at compile time.
- While building at run-time, we generate proofs as required.

**Comment by siddhartha-gadgil** [comment]
The use of existentials is blocking the effective use of indexed induction, as relevant types are hidden away. So this must be solved. Compile-time use of `Fold` must be eliminated.

**Comment by siddhartha-gadgil** [comment]
## Introduction rule types
* These should be a shapeless list, giving the type of all the introduction rules together.
* This mean the `ConstructorSeqDom` and the various convenience methods calling it should be parametrized.

## ConstructorSeqDom
* Should acquire intro parameter.
* Given `typ: Typ[C]` implicitly discover the `ConstructorSeqMap`.
* Use this in recursion.
* For induction, the codomains type `C` should be calculated from the type of the fibre.

## Indexed case
* `mapper`s should be implicitly defined given codomain.
* rec should use this, as well as implicit scala similar to the absolute case.
* The computation of codomain from iterated fiber is more involved and an implicit class may be needed just for this.

**Comment by siddhartha-gadgil** [comment]
To make introduction rules a type parameter for `ConstructorSeqDom`, we must also make the domain type `H` a parameter. There does not seem any reason to avoid this.

**Comment by siddhartha-gadgil** [comment]
* Rewritten so that types are exposed at compile time. 
* The tests in _InductionSpecTL_ run without `Fold`, i.e., with types correct.
* Informally, prepending to a vector is tested (in REPL session, should make test).

**Comment by siddhartha-gadgil** [comment]
Test for prepending vector incorporated, passed.

**Comment by siddhartha-gadgil** [comment]
* When codomains for induction are complicated, e.g. `PiDefn[u, v]`, recording `C` is does not allow inference as the type is _finer_ than `Typ[C]`. 
* Presumably we should be storing `TC = Typ[C]` all along, or at least both.

**Comment by siddhartha-gadgil** [comment]
* The crude sub-type method in the first attempt fails as the codomain `C` has to be determined before `TC`, and this is impossible.
* We need some version of the following, to calculate C via an implicit with a bound guarantee.
```
abstract class TypObj[T <: Typ[Term], C <: Term with Subs[C]](implicit ev: T <:< Typ[C]){
  def me(t : T) : Typ[C] = t
  }
```
* C is not magically inferred from a bound. We need to solve for it with cases.

**Comment by siddhartha-gadgil** [comment]
Sub-types are picked up using low priority implicits.

**Comment by DmytroMitin** [comment]
Yes, it works. Thank you.
