### ISSUE TITLE
Hygiena break for type of induction over double indexed inductive type

### ISSUE THREAD

**Issue by DmytroMitin** [siddhartha-gadgil/ProvingGround#116]
```
  val Nat = "Nat" :: Type
  val NatInd = ("0" ::: Nat) |: ("succ" ::: Nat -->>: Nat) =: Nat
  val zero :: succ :: HNil = NatInd.intros
  val n = "n" :: Nat
  val m = "m" :: Nat
  val Vec = "Vec" :: Nat ->: Type
  val VecInd = ("nil" ::: (Vec -> Vec(zero))) |:
      { "cons" ::: n ~>>: (Nat ->>: (Vec :> Vec(n)) -->>: (Vec -> Vec(succ(n)) ))} =:: Vec
  val vnil :: vcons :: HNil = VecInd.intros
  val Matrix = "Matrix" :: Nat ->: Nat ->: Type
  val MatrixInd = {"nil" ::: m ~>>: (Matrix -> Matrix(zero)(m))} |: 
       { "cons" ::: n ~>>: (m ~>>: (Vec(m) ->>: (Matrix :> Matrix(n)(m)) -->>: 
       (Matrix -> Matrix(succ(n))(m) )))} =:: Matrix
  val mnil :: mcons :: HNil = MatrixInd.intros
  val matnm = "mat_nm" :: Matrix(n)(m)
```
`MatrixInd.induc(n :~> (m :~> (matnm :-> Matrix(m)(n)))).typ.fansi` produces
`"(∏($m : { Matrix($m)(0) } → (∏($j : { ∏($j : { ∏($g : { ∏($r : { (Matrix($j)($j) → Matrix($j)(succ($j))) } } } } → ∏($h : { ∏($i : { ∏(mat_nm : { Matrix($i)($h) } } }))"`
instead of type with different `j1` and `j2`.

**Comment by siddhartha-gadgil** [comment]
Made changes that should have no effect but the problem seems to have disappeared.

**Comment by siddhartha-gadgil** [comment]
The fundamental problem was variable names were in a cycle instead of progressing (bug introduced during some past refactoring). This has been corrected.

**Comment by DmytroMitin** [comment]
Yes, it works. Thank you.
