### ISSUE TITLE
Wrong calculations with recursion to Nat ->: Nat ->: Nat

### ISSUE THREAD

**Issue by DmytroMitin** [siddhartha-gadgil/ProvingGround#118]
I tried to translate this code:
```
fib :: Int -> Int
fib n = fib_aux n 0 1
  where 
    fib_aux :: Int -> Int -> Int -> Int
    fib_aux 0 m1 m2 = m1
    fib_aux n m1 m2 = fib_aux (n-1) m2 (m1+m2)
```
I wrote 
  ```
import TLImplicits._
  import shapeless._
  val Nat = "Nat" :: Type
  val NatInd = ("0" ::: Nat) |: ("succ" ::: Nat -->>: Nat) =: Nat
  val zero :: succ :: HNil = NatInd.intros
  val one = succ(zero)
  val two = succ(one)
  val three = succ(two)
  val four = succ(three)
  val five = succ(four)
  val six = succ(five)
  val n = "n" :: Nat
  val m = "m" :: Nat
  val m1 = "m1" :: Nat
  val m2 = "m2" :: Nat
  val recNNN = NatInd.rec(Nat ->: Nat)
  val addn = "add(n)" :: Nat ->: Nat
  val add = recNNN(m :-> m)(n :-> (addn :-> (m :-> succ(addn(m)) )))
  val recNNNN = NatInd.rec(Nat ->: Nat ->: Nat)
  val fibn = "fib_aux(n,_,_)" :: Nat ->: Nat ->: Nat
  val fib_aux = recNNNN(m1 :-> (m2 :-> m1))(n :-> (fibn :-> (m1 :-> (m2 :-> fibn(m2)(add(m1)(m2)) ))))
  val fib = n :-> fib_aux(n)(zero)(one)
```
But this produces powers of 2 instead of fibonacci.
```
@ fib(zero) 
res48: Term = 0 : (Nat : 𝒰 _0)
@ fib(one).fansi 
res49: String = "succ(0)"
@ fib(two).fansi 
res50: String = "succ(0)"
@ fib(three).fansi 
res51: String = "succ(succ(0))"
@ fib(four).fansi 
res52: String = "succ(succ(succ(succ(0))))"
@ fib(five).fansi 
res53: String = "succ(succ(succ(succ(succ(succ(succ(succ(0))))))))"
@ fib(six).fansi 
res54: String = "succ(succ(succ(succ(succ(succ(succ(succ(succ(succ(succ(succ(succ(succ(succ(succ(0))))))))))))))))"
```

**Comment by siddhartha-gadgil** [comment]
The function `fib_aux` is giving the cumulative sum starting with `m1` and `m2`, instead of the sum of the two previous entries.

**Comment by DmytroMitin** [comment]
But Haskell's fib_aux 
```
fib :: Int -> Int
fib n = fib_aux n 0 1
  where 
    fib_aux :: Int -> Int -> Int -> Int
    fib_aux 0 m1 m2 = m1
    fib_aux n m1 m2 = fib_aux (n-1) m2 (m1+m2)
```
calculated correctly
```
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
Prelude> :l 1.hs 
[1 of 1] Compiling Main             ( 1.hs, interpreted )
Ok, modules loaded: Main.
*Main> fib 0
0
*Main> fib 1
1
*Main> fib 2
1
*Main> fib 3
2
*Main> fib 4
3
*Main> fib 5
5
*Main> fib 6
8
*Main> fib 7
13

```

**Comment by siddhartha-gadgil** [comment]
Another specific wrong calculation
```
@ fib_aux(three)(m1)(m2) == add(add(m1)(m2))(add(m1)(m2)) 
res40: Boolean = true
```

**Comment by siddhartha-gadgil** [comment]
As expected:
```
fib_aux(succ(n))(m1)(m2) ==  fib_aux(n)(m2)(add(m1)(m2))
```
But we have
```
@ fib_aux(three)(m1)(m2) ==  fib_aux(two)(m2)(add(m1)(m2)) 
res58: Boolean = false
```
And this persists even if we plug in `succ(two)` in place of `three`. 

This is clearly a bug. We also see
```
@ fib_aux(succ(n))(one)(one).replace(n, two).fansi 
res63: String = "succ(succ(succ(0)))"
@ fib_aux(three)(one)(one).fansi 
res64: String = "succ(succ(succ(succ(0))))"
@ fib_aux(succ(two))(one)(one).fansi 
res65: String = "succ(succ(succ(succ(0))))"
```

the first is correct but the second  wrong.

**Comment by siddhartha-gadgil** [comment]
An earlier point where this breaks:
```
@ def fn(t: Term) = FormalAppln.unapply(t).get._1 
defined function fn
@ fn(fib_aux(n)(m1)(m2)) 
res90: Term = ((<function1>) (n : (Nat : 𝒰 _0)) : ((Nat : 𝒰 _0) → ((Nat : 𝒰 _0) → (Nat : 𝒰 _0)))) (m1 : (Nat : 𝒰 _0)) : ((Nat : 𝒰 _0) → (Nat : 𝒰 _0))
@ fn(fn(fib_aux(n)(m1)(m2))) 
res91: Term = (<function1>) (n : (Nat : 𝒰 _0)) : ((Nat : 𝒰 _0) → ((Nat : 𝒰 _0) → (Nat : 𝒰 _0)))
@ fn(fn(fn(fib_aux(n)(m1)(m2)))) 
res92: Term = <function1>
@ fn(fn(fn(fib_aux(n)(m1)(m2)))) == fib_aux 
res93: Boolean = true
@ fn(fn(fn(fib_aux(succ(n))(m1)(m2)))) == fib_aux 
res94: Boolean = true
@ fn(fn(fn(fib_aux(succ(succ(n)))(m1)(m2)))) == fib_aux 
res95: Boolean = false
```

This means that we do have a formal application, but by a different function.

**Comment by siddhartha-gadgil** [comment]
A substitution that should change nothing (on branch debugtrace) is giving a different but still wrong answer. Problem seems to be with substitution of inductive type definitions, hence for nested inductive types. The change in code is
```diff
-  var crash = false
-
   case class DataCons[
       H <: Term with Subs[H], C <: Term with Subs[C], D <: Term with Subs[D]](
       data: D,
@@ -53,11 +51,7 @@ object RecursiveDefinition {
     def newobj = DataCons(data.newobj, defn, tail)
 
     def subs(x: Term, y: Term) =
-      {val result =  DataCons(data.replace(x, y), defn, tail.subs(x, y))
-        if (crash && data.replace(x, y) != data)
-          throw new IllegalArgumentException(s"Attempting to substitute $x by $y in $data getting ${data.replace(x, y)}")
-        result
-      }
+      DataCons(data.replace(x, y), defn, tail.subs(x, y))
```

the result depends on whether `crash` is true or false, and with behaviour repeated when making switches.

**Comment by siddhartha-gadgil** [comment]
### Diagnosis (should be confirmed by fixing).

* This is a subtle error caused by _bound variables escaping scope_, or more accurately, the same bound variable being used in two lambdas, one nested in the other.
* This normally does not happen as new variables are created and used when defining a lambda.
* However, when we compute `fib_aux(succ(n))`,
  - in specifying the data defining `fib_aux`, variables `m1` and `m2` are generated. 
  - the result is a function, which is a lambda of the form `m1 :-> m2 :-> y`.
  - but the `y` itself involves a formal application of `fib_aux`, and the definition of `fib_aux` uses the data which has the same bound variables `m1` and `m2`.
  - this means that when we apply the function `fib_aux(succ(n))`, we substitute arguments for `m1` and `m2`. But these substitutions also have an effect on the definition of `fib_aux` as this uses the same variables.
* It is clear that  such substitutions are happening, and they should not. Of course one has to test after correcting whether this is the only source of error.
* A solution is to _sanitize_ the data in recursive definitions before using in a formal application, i.e., with the data not changed but using freshly generated variables for lambdas. This can be done by using translation from `Term` to `Term`, but will first try a simpler implementation.

**Comment by siddhartha-gadgil** [comment]
The above was done (crudely) and seems to have partially worked: the bug #120 seems to be fixed, and manually applying the recursion definition in this case works okay. But the main bug persists.

**Comment by siddhartha-gadgil** [comment]
With another change, `fib` seems to work. But:
  - the change should also be made for indexed types.
  - a better `rebuild` should be used, including for example products.
  - computations have slowed down, may need an _opt-out_ - for example to use a specified rebuilder, perhaps one that is just the identity.
