### ISSUE TITLE
Bug in the reduce method of FreeGroups.Word.

### ISSUE THREAD

**Issue by Bolt64** [siddhartha-gadgil/ProvingGround#12]
Ideally, applying the reduce function on Word(List(1,2,-2,-1)) should return the empty word, but what it returns is  the word a.a!. I'll fix this bug and send a pull request.

**Comment by siddhartha-gadgil** [comment]
I see the problem. In the third case we have
        case x :: ys => x :: Word(ys).reduce

The code falls back to this case only after checking that the first two letters don't cancel in the original word. But if they cancel after reduction of ys, no further reduction is done.

One should instead have 
if (Word(ys) == Word(ys).reduce) x :: Word(ys).reduce 
else (x :: Word(ys).reduce).reduce

It would be even better to define an isReduced method and use it for cleaner code.

**Comment by siddhartha-gadgil** [comment]
Corrected in branch correctReduction. Pull to master to merge with other changes.
