### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by newca12** [siddhartha-gadgil/ProvingGround#126]
Impressive work.
Which license is Proving Ground source code published under?

**Comment by siddhartha-gadgil** [comment]
Thanks. MIT licence.

**Comment by newca12** [comment]
Great !
Would you mind to make it clear and add MIT License text to the root of the project. please
I would then be happy to contribute as much as I can.

**Comment by siddhartha-gadgil** [comment]
Thanks. I would greatly appreciate contributions.
I have moved the license to the root from a sub-folder, where it was
accidentally.

**Comment by newca12** [comment]
Thanks.
