### ISSUE TITLE
No graph hierarchy in generated Scaladoc

### ISSUE THREAD

**Issue by newca12** [siddhartha-gadgil/ProvingGround#129]
What OS did you use to generate the Scaladoc ?
graphviz need to be installed (providing the required "dot" binary)

**Comment by siddhartha-gadgil** [comment]
I just installed graphviz and am re-running everything.

**Comment by siddhartha-gadgil** [comment]
Generated now. Very nice - thanks. Should clean up api upload.

**Comment by newca12** [comment]
Great.
Thanks.
