### ISSUE TITLE
`sbt mantle/test:console` doesn't bring up a Ammonite REPL

### ISSUE THREAD

**Issue by hongchangwu** [siddhartha-gadgil/ProvingGround#137]
It just runs a normal Scala REPL with no imports.

**Comment by siddhartha-gadgil** [comment]
I have upgraded ammonite, so it should be ammonite/test:run but with a
quirk -  if there is an error one has to create an empty folder. Will
update readme

**Comment by newca12** [comment]
> so it should be ammonite/test:run

I guess you meant : sbt mantle/test:run
Regarding the issue with empty folders, I have pushed a PR to Ammonite to fix this.
This PR has been merged into master so we just have to wait for Ammonite 0.8.6 to be published.

**Comment by siddhartha-gadgil** [comment]
Thanks for the fix.
I do mean sbt mantle/test:run. There is also a server as explained in the
README

**Comment by siddhartha-gadgil** [comment]
The correct command is in both the README and the web page
