### ISSUE TITLE
What does the function wordWeight return?

### ISSUE THREAD

**Issue by Bolt64** [siddhartha-gadgil/ProvingGround#14]

**Comment by siddhartha-gadgil** [comment]
it should return the probability of generating a word for a generation process where we:
* start with the empty word.
* at each step choose a 0-1 variable T with probability of 1 being wrdCntn
* if T is 1, choose a generator or inverse of a generator uniformly and extend the word by multiplying with the generator.
* if T=0, stop and give the resulting word.

This terminates evenetually with probability 1.
