### ISSUE TITLE
Should store the relators of a presentation in an unordered list.

### ISSUE THREAD

**Issue by Bolt64** [siddhartha-gadgil/ProvingGround#16]
Currently, the words describing the relators of a presentation are stored in a List, which makes the order important, hence Presentation(List(a,b), 2) is not the same as Presentation(List(b,a), 2), but both actually are the same presentation. I suggest replacing the List here with a multiset, so the order does not matter, only the multiplicities.

**Comment by siddhartha-gadgil** [comment]
We probably need a list, as we want moves such as invert relation 2 to be
well defined
