### ISSUE TITLE
Should ACstabilized have this behaviour?

### ISSUE THREAD

**Issue by Bolt64** [siddhartha-gadgil/ProvingGround#17]
Consider the presentation $\langle a; a \rangle$. This is AC stabilized, but applying the ACstabilized method on it returns false.

**Comment by siddhartha-gadgil** [comment]
It's a bug.

**Comment by Bolt64** [comment]
As far as understand, ACstabilized is supposed to return true if the relations of the presentation contain the word Word(List(rank)). That is to say <a,b,c,d ; a.b, c.a, d> is ACstabilized whereas <a,b,c,d ; a.b, c.a, c> is not. Is this the expected behaviour.

**Comment by siddhartha-gadgil** [comment]
Can you rewrite the comment avoiding less than symbol. Markdown mangles the
text.

**Comment by siddhartha-gadgil** [comment]
Yes, it is as per your example. ACstabilized means is the result of AC stabilization of some presentation.
