### ISSUE TITLE
Normal forms for commutative, associative operations

### ISSUE THREAD

**Issue by siddhartha-gadgil** [siddhartha-gadgil/ProvingGround#2]
* Even if sum : A -> A -> A is a commutative associative operation, the terms below are distinct:
    * lambda(x)(lambda(y)(sum(x)(y))) 
    * lambda(x)(lambda(y)(sum(y)(x))) 

* This not only blows up the evolving state but gives wrong semantics for back-propagation and purging.

* One needs to represent such sums differently:
    * Have types MultiSet(A) parametrized by types A, represented by Map[A, Int].
    * Have types Big(A)(f: A -> A) for Sigma, Pi etc.
    * Rewrite results of commutative operations in terms of these.

* This makes sums definitionally equal if they are equal using commuting.

* Similar considerations apply for associative operations (with List(A) instead of MultiSet(A)).

* Distributive pairs of operations should have appropriate normal forms too.

**Comment by Bolt64** [comment]
If the "addition" and "multiplication" are associative in the distributive pair, then we can represent it by a List[List[A]], for example, (a(b+c)+d) simplifies to (ab+ac+d), so that gets represented as List(List(a,b), List(a,c), List(d)). However, if one or both the operations are not associative, I'm not sure we can use this representation.

**Comment by siddhartha-gadgil** [comment]
True, distributivity is useful only if the underlying operations are
associtive at least - presumably we need the "+" to be commutative as
well.Specifically:

(1) We have representations of + by List or MultiSet, both of which have
"map" methods.

(2) Thus, we write terms built with "+" as Big(+)(A), where A is a list or
a multiset.

(3) We can define "term-wise multiplication" by using the map operation in
both these cases.

(4) Now any product b * (Big(+) A) is rewritten as Big(+) (b * A), where (b
* A) is the pointwise product.

**Comment by Bolt64** [comment]
Also, I don't think the MultiSet representation works for operations that are commutative but not associative. For example, consider this operator ?. x ? y = xy+1. Clearly this operator is not associative, but the MultiSet representation of x ? (x ? y) is the same as that of (x ? x) ? y, which is obviously wrong. Instead, for commutative but not associative operations, we could have a tree of 2-tuples, with equality operator being overloaded such that (a,b)==(b,a).

**Comment by siddhartha-gadgil** [comment]
True, but in mathematics commutative operators are usually associative.

**Comment by Bolt64** [comment]
Another question. Do we need the representations to be covariant in their type parameters, or is it fine if they're just invariant?

**Comment by Bolt64** [comment]
If we want covariance, we'll have trouble with our Map representation of multiset because a scala Map is invariant in its first parameter.

**Comment by siddhartha-gadgil** [comment]
Good point, but we probably don't need covariance. Otherwise we can
construct by hand a multiset with map, flatMap and filter (may be already
in the Collections object in the core project).

**Comment by siddhartha-gadgil** [comment]
I was trying to use map so that there is an efficient implementation of
equality (using hash trees etc).

**Comment by Bolt64** [comment]
Another question about the Big representation. When we're adding two sigmas, like Big(+)(List(1,2,3)) + Big(+)(List(4,5,6)), it makes sense to concatenate the representations and then return Big(+)(List(1,2,3,4,5,6)). But what about something like this; Big(*)(List(1,2,3)) + Big(*)(List(4,5,6))? Do I represent it as Big(+)(List(Big(*)(List(1,2,3)), Big(*)(List(4,5,6))) or do I evaluate the Pi before putting it in the sigma, something like this; Big(+)(List(6, 120))?

**Comment by siddhartha-gadgil** [comment]
Operations should be eager, so that if we are adding numbers (rather than symbols), we should just add them. This means we should collapse collections in Big(+) so if any pair is numbers (with multiplicity), they should be replaced by a single number. In fact even a single element with multiplicity not 1 should be replaced by its product with its multiplicity.

**Comment by siddhartha-gadgil** [comment]
Second version (using ideas from NormalForm code) written. This is integrated with both HoTT and spire.
