### ISSUE TITLE
How exactly are the presentation and the sequence of moves stored in the FiniteDistribution?

### ISSUE THREAD

**Issue by Bolt64** [siddhartha-gadgil/ProvingGround#20]
As far I have understood, each vertex in the finite distribution for andrewscurtis will contain presentation and a sequence of moves. But the moves have been implemented as methods of the case class rather than functions in the companion object. If they were implemented as functions in the companion object, we could have represented a presentation and the associated moves in this manner

    (Presentation(2, "a!ba", "b!ab"), List[Presentation => Presentation](<a list of moves>))

That way, to get the resultant presentation from the original, we just compose the functions in list of moves, and apply it on the original presentation. But if the moves are implemented as methods, this kind of representation might not be possible.

**Comment by siddhartha-gadgil** [comment]
That's correct. So we need functions in the companion object corresponding
to the moves - they can just call the methods, or we can move methods over
to the object as functions.

**Comment by Bolt64** [comment]
Yes, that's what I was thinking of as well. It should work fine, I suppose.
