### ISSUE TITLE
Applying a move on both FD[V] and FD[Pres].

### ISSUE THREAD

**Issue by Bolt64** [siddhartha-gadgil/ProvingGround#23]
I implemented the method to apply a single move M to FD[V] and that works just fine. However, if we want to implement the apply method also for FD[Presentation], then we will have problems because of type erasure. The compiler will think both the apply methods have the same type signature and throw an error because of the double definition. One way to get around this could be to wrap the FD[V] and FD[Pres] in different case classes, but that's not very elegant. What do you think I should do?

**Comment by siddhartha-gadgil** [comment]
Firstly there is no type erasure at compile time, only at runtime. So there
should be no problem.

**Comment by Bolt64** [comment]
It doesn't work out. The compiler does throw an error when trying to compile if both the methods are implemented. As an example, you could try compiling this toy example with scalac, the compiler will complain. 
https://gist.github.com/Bolt64/cab3432322c645567678

**Comment by siddhartha-gadgil** [comment]
I'll try. But the more serious answer: you don't need the action on P, at
least for now.

Siddhartha

**Comment by siddhartha-gadgil** [comment]
You were right about type erasure. But the second point, as far as I can
see, you do not need moves to be actual functions, i.e., the action need
not be the apply method.

Siddhartha

**Comment by Bolt64** [comment]
In that case, I'll just implement the action on FD[Presentation] as some other method, and leave it at that.
