### ISSUE TITLE
What to do after a creating the function from (M, FD[V]) -> FD[V]?

### ISSUE THREAD

**Issue by Bolt64** [siddhartha-gadgil/ProvingGround#24]
What was the next thing we are supposed to do after we have a function from (M, FD[V]) -> FD[V]?

**Comment by siddhartha-gadgil** [comment]
Use extendM, the iterate

**Comment by Bolt64** [comment]
Stupid question, but what is extendM, again?

**Comment by siddhartha-gadgil** [comment]
My answer was wrong. You first need to use weightedDynSystem. I will be
more precise when I can see code.

**Comment by siddhartha-gadgil** [comment]
I now see that weightedDyn just gives a single term. We then use vBigSum to
add these. Finally use extendM

**Comment by siddhartha-gadgil** [comment]
I again missed a step. I will write clearly from home.

**Comment by siddhartha-gadgil** [comment]
The missing step was using the differentiable function eval.

**Comment by siddhartha-gadgil** [comment]
Hopefully a coherent reply. Should put this on the wiki.

Overview: We construct a differentiable function in pieces. The forward function itself is a one-liner, but the gradient is cleaner in steps.

1. We start with moves, associating to an object of type M a function V => Option[V[

2. Applying moveFn gives, for an element m of M, a function f(m): FD[V] => FD[V].

3. now applying weightedDyn gives, associated to m, a function (FD[M], FD[V]) => FD[V] taking (p, m) to p(m)f(m), with f(m) the function associated to the move m and p(m) the weight at m.

4. Given a collection of moves, say List[M], we can map to a collection of function (FD[M}, FD[V]) => FD[V]).

5. Using an implicit vector space structure, we use vBigSum to add the above collection to get a function (FD[M], FD[V]) => FD[V].

6. Now use extendM to get a function (FD[M], FD[V]) => (FD[M], FD[V])

7. Use Diffblefunction.iterate to create an iteration for fixed n.

8. Finally, use project and a map induced (using moveFn) by a function from V to P. We get a function (FD[M], FD[V]) => FD[P], depending on how many times we iterate, We conjugate the feedback by this.

**Comment by Bolt64** [comment]
Could you explain the third step in a little more detail? What are we applying weightedDyn on?

**Comment by siddhartha-gadgil** [comment]
For ecah move m in M, we apply weightedDyn on the pair (m, f), where f is
the function on FD [M] corresponding to m

**Comment by Bolt64** [comment]
I'm getting a type mismatch when I'm trying that. In my case, m is of the type V => Option[V], and f is of the form FD[V]=>FD[V]. weightedDyn requires linearStructure and innerProduct as its first and second arguments.

**Comment by siddhartha-gadgil** [comment]
I think you have hit an implicit quirk of scala which I have faced many
times - it is looking for implicit arguments, and telling you their types.
Try to split into two lines:

val wtdDyn = weightedDyn[V => Option[V], FD[V]]
wtdDyn(m, f)

One can make (m, f) as arguments to avoid this roundabout way.

**Comment by siddhartha-gadgil** [comment]
Pushed a note on all this to wiki (but not the implicit quirk - we should
change the signature so type inference works).

**Comment by Bolt64** [comment]
The second argument of wtdDyn requires a DiffbleFunction[FD[V], FD[V]]. However, f is just a function FD[V]=>FD[V]. Is it supposed to implicitly convert a function of type FD[V]=>FD[V] to a diffbleFunction, or do I have to convert it to the appropriate form?

**Comment by siddhartha-gadgil** [comment]
You do need to build and use a differentiable function. This comes
automatically if you use moveFn to create the function given the move V =>
Option[V]

**Comment by Bolt64** [comment]
I have another question about step 8. Doing everything as you've said until step 7, I have a differentiable function from (FD[M], FD[V])=>(FD[M], FD[V]). Now what am I applying the projectV function on?

**Comment by siddhartha-gadgil** [comment]
You compose an iteration of the function constructed with project, the with
the function to FD[P] obtained using moveFn

**Comment by siddhartha-gadgil** [comment]
Alternatively, construct a separate function using projectV and the the map
to FD[P] and pull back the feedback along this. This can in turn be pulled
back by an iteration of the function you constructed

**Comment by Bolt64** [comment]
OK, so now after composing the differentiable functions, I have a function of the type (FD[M], FD[V]) => FD[P]. Now what do I do?

**Comment by siddhartha-gadgil** [comment]
Conjugate the feedback on FD[P] by the function you constructed to get a
feedback on (FD[M], FD[V]). Evolve along this. Make sure your moves include
the identity

**Comment by Bolt64** [comment]
What do you mean by the feedback on FD[P]?

**Comment by siddhartha-gadgil** [comment]
1. Given weights on P and an object in FD[P], we have a "feedback"
returning an element of FD[P]. This is a flow towards the given weights. It
is implemented (but not tested) as feedback.

2. On P we have given weights, should again be implemented (but not tested).

3. We thus get a function FD[P] => FD[P].

4. We can conjugate this by the differentiable function you have
constructed to get a function (FD[M], FD[V]) => (FD[M], FD[V]).

5. We scale (at some stage) by a parameter epsilon.

6. Now we  get a dynamical system, which is supposed to do the learning.

**Comment by Bolt64** [comment]
From what I've seen, the feedback method applied to a FD[P], returns another FD[P], but this time all the weights summing up to zero. I suppose I add this feedback to the original FD, and this way I have new weights on the presentations. Is that the function you mention in step 3, FD[P]=>FD[P]?

**Comment by siddhartha-gadgil** [comment]
Indirectly yes. Actually you conjugate this to get such an element of
(FD[M], FD[V]), and this gives dynamics by adding this. We however multiply
by epsilon before adding. Further, we normalize to remove negative
probabilities.

**Comment by Bolt64** [comment]
What exactly is conjugation here?

**Comment by siddhartha-gadgil** [comment]
Look for a method with that in the comments, for differentiable functions

**Comment by Bolt64** [comment]
Ok, so now conjugating the DiffbleFn (FD[M], FD[V])=>FD[P] with the function FD[P]=>FD[P], we get a function (FD[M], FD[V]) => (FD[M], FD[V]). Now what exactly are we scaling? And how do we determine what epsilon to scale by?

**Comment by siddhartha-gadgil** [comment]
We pick a parameter for the dynamics,  epsilon, which is the step size.
Like the number n of iterations, we vary this and see what happens.

**Comment by Bolt64** [comment]
Here's what I have done so far:

1. Created a differentiable function d of the type (FD[M], FD[V]) => FD[P].
2. Created a function g that takes f: FD[P], and returns f + f.feedback.
3. Conjugated d with g. This gave me a function of the type (FD[M], FD[V]) => (FD[M], FD[V]).

I'm not very sure whether step 2 is correct or not. The weights in the feedback I'm getting are very small.

**Comment by siddhartha-gadgil** [comment]
You should be "exchanging" steps 2 and 3, i.e., conjugate the feedback to
get a function (FD[M], FD[V]) => (FD[M], FD[V]) with all entries in the
image having total (0, 0). Dynamics are given by (m, v) mapping to (m, v) +
(corresponding feedback).

**Comment by siddhartha-gadgil** [comment]
I cannot understand what  are the dynamics. I thought in (M, V), V =
List[Move]. But I cannot find a differentiable function on [M, V]

**Comment by siddhartha-gadgil** [comment]
I now notice that Moves is a wrapper for list of moves. I will continue
reading code and experimenting.

**Comment by Bolt64** [comment]
Sorry about that. Should have added comments describing the case classes and the functions.

**Comment by siddhartha-gadgil** [comment]
I will add comments and refactor. The damping for the feedback should also
be changed (I'll do that).
