### ISSUE TITLE
Allow generation by a mixture

### ISSUE THREAD

**Issue by siddhartha-gadgil** [siddhartha-gadgil/ProvingGround#259]
* The entropy of a mixture can be, for example, the exponent of the sum of the logs of the entropies.
* More generally one can take concave functions, and adjust this to encourage splitting (but logs may just work automatically).

**Comment by siddhartha-gadgil** [comment]
Better to have local optima where we have a cost for unproved theorems.

**Comment by bollu** [comment]
Can I have some more context? What is this referring to (in terms of `splitting`?)

**Comment by siddhartha-gadgil** [comment]
I meant taking multiple initial distributions, generating separately with
these and combining the results. But my approach may change.

regards,
Siddhartha

**Comment by siddhartha-gadgil** [comment]
Approached changed to adversarial optima, #260
