### ISSUE TITLE
Extremely slow running: presumably too many objects created

### ISSUE THREAD

**Issue by siddhartha-gadgil** [siddhartha-gadgil/ProvingGround#33]
Running is absurdly slow, even when the population size is a few thousand. 

## Possible Diagnosis

This is caused by a combination of 

* creating objects for differentiable functions (by itself this is fine)
* passing the methods that create such objects using _call by name_
* as a result, a whole bunch of new differentiable function objects are created every time the function is to be applied, i.e. for every element in the population.
* this is slow, and also creates garbage so rapidly that the system starts crawling.

## Example

* suppose we have 
```scala
  val f = ...
  val a : DiffbleFunction...
  
  def m = movefn(f)
  val b = vsum(a, m)
```

* Then vsum is an operation to which m is passed _by name_, i,e,, not computed and passed but passed as a definition.
* This definition involves creation of a new object every time a method (such as apply) of m is called, i.e., for every term.
* We can avoid some cases like this with a val, but as we have iterated sums, we will be passing **defs**, and so creating a lot of objects.

## Solution

* Avoid the call by name recursion (which happens when we use the DiffbleFunction constructor).
* Instead have separate case classes for moves, sums etc, (or an eager constructor for Diffble Functions).
* Use some other method for islands, when we get to it - the problematic method was used for enough generality to easily include islands.

## Addendum

Using repeated summing for a _bigsum_ of differentiable functions is needlessly inefficient. There should just be a big sum case class.

**Comment by siddhartha-gadgil** [comment]
Naively switching to call by value **did not** solve the problem.

**Comment by siddhartha-gadgil** [comment]
The above may miss the key point. There are probably too many objects being created, because differentiable functions are created repeatedly. But the real cause may be because the apply method is a def (as it needs to be) in terms of given functions, which are in terms of apply methods of other objects. This means the other objects are created every time. Namely, we have
```scala
	trait DiffbleFunction[A, B] extends Any{self =>
      def apply(a: A): B

    	def grad(a: A) : B => A
...
}
```

We should instead have _values_ **func** and **grad**
```scala
trait DiffbleFunction[A, B]{
   val func: A => B

   val grad : A => B => A

   def apply(a: A) = func(a)
...
}
```

with these being lazy in many concrete sub-classes. This should avoid objects being repeatedly created (can check by logging on creating objects).

**Comment by siddhartha-gadgil** [comment]
### Sample REPL seesion

Illustrates that 

* def creates new objects on each call
* val does only on construction
* lazy val does only on first call. 

```scala
@ case class Fn(func: Int => Int)
defined class Fn
@ case class Fn(func: Int => Int){
  println("object created")
  }
defined class Fn
@ Fn((x: Int) => x *2).func(2)
object created
res6: Int = 4
@ Fn((x: Int) => x *2).func(3)
object created
res7: Int = 6
@ val D = Fn((x: Int) => x *2)
object created
D: Fn = Fn(<function1>)
@ D.func(2)
res9: Int = 4
@ D.func(3)
res10: Int = 6
@ val f = Fn((x: Int) => x *2).func
object created
f: Int => Int = <function1>
@ f(2)
res12: Int = 4
@ f(3)
res13: Int = 6
@ def g(a: Int) = Fn((x: Int) => x *2).func(a)
defined function g
@ g(2)
object created
res15: Int = 4
@ g(3)
object created
res16: Int = 6
@ lazy val h = Fn((x: Int) => x *2).func
h: Int => Int = <lazy>
@ h(2)
object created
res18: Int = 4
@ h(3)
res19: Int = 6
```

**Comment by siddhartha-gadgil** [comment]
Avoided most defs - only ones remaining are those of the implicit conversion from AtomicMoves. Runs slowly still. Should correct this, but  also investigate running behaviour in detail (example - use futures, log).

**Comment by siddhartha-gadgil** [comment]
Nothing uses defs now, but still runs slowly.

**Comment by Bolt64** [comment]
Maybe we should do a proper runtime profiling of the code. Figure out which function calls take up the most time? I don't know about scala profiling tools, but we could try and use visualvm. That way, we can figure out if the bottleneck is because of the defs, or something else.

**Comment by siddhartha-gadgil** [comment]
Yes, we should. I have never used tools like these. I will also try just
varying various things and logging while running concurrently.

**Comment by Bolt64** [comment]
I'm getting some compiler warning about the method apply being deprecated in DiffbleFunction. Is that expected behaviour?

**Comment by siddhartha-gadgil** [comment]
Yes. You should use func.

**Comment by Bolt64** [comment]
It seems that this particular method AbstractSeq.equals() is taking up roughly 40 to 50% cpu time.

**Comment by siddhartha-gadgil** [comment]
This will happen when comparing whether two sequences of moves are equal or
not, when adding together two finite distributions. We even get this while
applying moves, as moves may not be injective. So the population is
converted to a sequence, mapped by moves and then _flattened_, with
Weighted(a, x) and Weighted(a, y) joined together.

The number of such comparisons is the square of the population being
constructed - actually the square of the raw population, i.e., without
merging. This is large - while evolving to 3 steps, the population size is
more than 2000, so about 5 million comparisons need to be made.

This seems inevitable as a nature of the problem, not a limitation of code.
We can manage this by pruning populations (or selecting sub-populations on
which to make moves). We can also run in parallel to speed up.

For the present, I see even 3 steps should give interesting results for
learning. I'll write about this in the wiki.

**Comment by siddhartha-gadgil** [comment]
_Inevitable_ is an overstatement - for forward propagation at least, when
the moves are injective, we can use Sequences or Vectors instead of sets to
avoid the comparison slowing. Vectors are good for sampling too. But when
we compute a feedback we do need to fold a finite distribution, i.e.,
aggregate elements, so we do not have much gain directly.

In the longer run, we should abstract finite distributions with sets as one
representation.

**Comment by Bolt64** [comment]
Alternatively, at least for the case classes we have, we could override equality with a faster implementation using hashes. Since all our data structures are immutable, we can compute the hash value only once, when the data structure is first constructed, and subsequently compare the hash values instead of comparing the actual sequence. This will be amortized O(1) instead of O(n) and could speed things up.

**Comment by Bolt64** [comment]
And for sequences where order is not important (like finite distributions), we combine the hash values of the elements of the FD using a commutative operator to get the hash value for the FD. On the other hand, where the order is important, like sequences of moves, we combine the hash values using a non commutative operator.

**Comment by siddhartha-gadgil** [comment]
That will help, but not solve the main problem. This is not slowness in
comparing sequences, but rather the large number of pairs of sequences that
need to be compared. As we compare all pairs, this scales by the square of
the population, which grows fast (without pruning or selecting at some
stage). Speeding up each comparison will reduce the scale factor, but we
are already seeing a slowdow with sequences of length 3 or 4.

**Comment by Bolt64** [comment]
In that case we should probably make sure this runs well in parallel. What changes will we need to make in the code to make it run in parallel?

**Comment by siddhartha-gadgil** [comment]
I can think of some things based on the conjecture that most of the time is
spent in Weighted.flatten, which involves grouping together various
elements. This is by no means the only way to parallelize, but the best I
could think of for now.

* Firstly, we have an explicit bigsum (over moves in our case) rather than
iterated sums, so we have more control.
* We split each sequence (a sequence corresponds to a move) into groups
based on hash code (or some more semantic invariant), so that only elements
in the same group can be equal. This can be done in parallel for the
different groups.
* For each sequence, we flatten together those in a group. Again different
groups can be done in parallel.
* We then fold together corresponding classes of the different sequences,
again in parallel.
* Finally, we can concatenate sequences without any need to flatten.
* All this can be done idiomatically by flatMapping futures, without any
need for explicitly sequencing the steps.
* We should probably be using vectors rather than sequences.
* In the actual HoTT case, we can naturally split by types.
* Even if there is no a priori spltting, we can do a flattening after first
splitting a sequence (vector will be much better) by indices, and then
doing the above.

**Comment by siddhartha-gadgil** [comment]
The parallelization mentioned above assumes the internal representation for
Finite Distributions is not a set as at present, but a vector/sequence.

**Comment by siddhartha-gadgil** [comment]
The above method I sketched is needlessly complicated. All we have to do is:

* Use a Vector for the pmf for Finite Distributions, not Set (so scala does
not try to flatten).
* Flatten explicitly and only when needed.
* When flattening:
  * Group by hash code of the element modulo N, for N parallel streams.
  * Flatten each one separately (as a Future)
  * When all futures are ready, fold using concatenation (there is a
Future.sequence method we can use).
