### ISSUE TITLE
Did the latest commit break something?

### ISSUE THREAD

**Issue by Bolt64** [siddhartha-gadgil/ProvingGround#36]
ACevolution.evolve isn't evolving the finite distribution as expected. It's just creating a uniform distribution on the atomic moves and never evolving it. Is this expected behavior?

**Comment by siddhartha-gadgil** [comment]
Clearly I broke something,  probably either MoveFn or summing
distributions. Many things were changed in FiniteDistributionLearner

**Comment by siddhartha-gadgil** [comment]
I think there are tests for MoveFn, but not summing finite distributions
etc.

**Comment by siddhartha-gadgil** [comment]
I had made a silly mistake in the empty Finite Distribution. I have
corrected it. Can you check now?

**Comment by siddhartha-gadgil** [comment]
Things are behaving as expected.
(1) The first component does not evolve at all without feedback.
(2) The second component, which is a distribution on moves, is evolving.
Siddhartha
