### ISSUE TITLE
Possible bottleneck in the code

### ISSUE THREAD

**Issue by Bolt64** [siddhartha-gadgil/ProvingGround#37]
There are still many hash collision happening, either because of poor hashing, or too many objects. In the case of hash collisions, toSet and distinct are faster on parallel collections than serial; we should try changing things to parallel and see if they work better.

**Comment by siddhartha-gadgil** [comment]
Let us try to locate where the collisions are happening. I am working on creating generic tests for finite distributions, so we can change implementation, including a trivial 
Weighted.flatten, to see if flattening is the bottleneck.

**Comment by siddhartha-gadgil** [comment]
if you like, you can try to make Weighted.flatten trivial in the set implementation itself. This will give in general wrong answers, but should behave correctly in terms of speed.

**Comment by Bolt64** [comment]
Yes, we could do that in a separate branch, and just see how long it takes.

**Comment by siddhartha-gadgil** [comment]
I have implemented Finite Distributions using vectors as well. Tests are written generically, and both implementations (Sets and Vectors) pass.
One can change default implementation to vectors and make Weighted.flatten to be identity. For forward evolution this gives the correct answer.

**Comment by siddhartha-gadgil** [comment]
The vector implementation is much faster even without making Weighted.flatten into the identity. We can try to work with this and see how things go.

**Comment by siddhartha-gadgil** [comment]
Once vectors are made the default implementation (as is now the case)

* performance is reasonable
* making Weighted.flatten to identity does not seem to speed things that much (just impressionistic testing).

It seems the best course is:

* proceed with vectors as implementation:
      * add more tests
      * see how learning works.
* implement also parallel vectors, with all methods using futures.

**Comment by Bolt64** [comment]
Parallel vectors will have a(an) (significant?) overhead if all we're over doing operations that can't be paralllelized and/or are linear in time. toSet is generally linear in time unless we have hash collisions, in which case it becomes quadratic, and only then does parallel.toSet become faster than serial.toSet.

**Comment by siddhartha-gadgil** [comment]
As I mentioned, map, flatMap and filter are used for moves, and these
should speed up

**Comment by Bolt64** [comment]
But we're using map, flatMap and filter nevertheless, so parallel vectors are a good idea.
