### ISSUE TITLE
Is pruning happening in the evolve function yet?

### ISSUE THREAD

**Issue by Bolt64** [siddhartha-gadgil/ProvingGround#47]
I've noticed that the evolve function slows down for larger arguments. Is the pruning not yet implemented, because if it is, then the evolve function should take roughly a constant time to run.

**Comment by siddhartha-gadgil** [comment]
It should be there, but I have not tested it. Try logging support size.

**Comment by Bolt64** [comment]
No, the pruning does not seem to be happening. The support of ACevolve.evolve(2,2) is of the size 225. The support for evolve(2,3) is 3375, which is 15 times the previous one, and for evolve(2,4). it's 50625.

**Comment by siddhartha-gadgil** [comment]
Sorry, the correct answer is pruning should be happening in the run and
next methods for the case class Path in SimpleACevolution. These methods
include feedback, so they are the ones to be used for iterated running.
